Update k8s.io/kubernetes to fix GO-2024-2746
kubernetes-sigs/gcp-filestore-csi-driver pull request #878
Opened 2024-06-10 21:54 UTC by hime

2024-06-10 22:07 UTC, tyuchn commented
/ok-to-test
Kindly reminder, don't forget to add a release note in this PR

2024-06-11 00:10 UTC, hime commented
/test pull-gcp-filestore-csi-driver-e2e

2024-06-11 03:57 UTC, tyuchn requested changes
/lgtm

2024-06-11 03:57 UTC, tyuchn commented on pkg/releaselock/rpc.go
> -	klog.Infof("Sending RPC request %+v from GKE node IP to Filestore IP %s", request, clientIP, hostIP)
I think this should change to 
```
klog.Infof("Sending RPC request %+v from GKE node IP %s to Filestore IP %s", request, clientIP, hostIP)
```

2024-06-11 14:51 UTC, hime commented
/test pull-gcp-filestore-csi-driver-e2e

2024-06-11 16:51 UTC, hime commented
/test pull-gcp-filestore-csi-driver-e2e

2024-06-11 17:10 UTC, hime commented on pkg/releaselock/rpc.go
> -	klog.Infof("Sending RPC request %+v from GKE node IP to Filestore IP %s", request, clientIP, hostIP)
Done.

2024-06-11 17:38 UTC, tyuchn approved these changes

2024-06-11 20:49 UTC, tyuchn commented
/lgtm
/approve

2024-06-11 20:50 UTC, merged

2024-06-13 20:04 UTC, hime commented
/cherry-pick release-1.6